var focus_items = document.querySelectorAll('.focus');
var focus_title_items = document.querySelectorAll('.focus-title');
var focus_content_items = document.querySelectorAll('.focus-content');
for(var f = 0; f < focus_items.length; f++){
	var focus_itemId = 'focus-item-id-' + (f+1);
	var focus_contentId = 'focus-content-id-' + (f+1);
	focus_items[f].id = focus_itemId;
	focus_content_items[f].id = focus_contentId;
}
$('.focus-content').hide();

$('#focus-item-id-1').click(function(){
    $('#focus-content-id-1').toggle('slow');
});
$('#focus-item-id-2').click(function(){
    $('#focus-content-id-2').toggle('slow');
});
$('#focus-item-id-3').click(function(){
    $('#focus-content-id-3').toggle('slow');
});
$('#focus-item-id-4').click(function(){
    $('#focus-content-id-4').toggle('slow');
});
$('#focus-item-id-5').click(function(){
    $('#focus-content-id-5').toggle('slow');
});
$('#focus-item-id-6').click(function(){
    $('#focus-content-id-6').toggle('slow');
});
$('#focus-item-id-7').click(function(){
    $('#focus-content-id-7').toggle('slow');
});
$('#focus-item-id-8').click(function(){
    $('#focus-content-id-8').toggle('slow');
});
$('#focus-item-id-9').click(function(){
    $('#focus-content-id-9').toggle('slow');
});
$('#focus-item-id-10').click(function(){
    $('#focus-content-id-10').toggle('slow');
});
$('#focus-item-id-11').click(function(){
    $('#focus-content-id-11').toggle('slow');
});
$('#focus-item-id-12').click(function(){
    $('#focus-content-id-12').toggle('slow');
});
$('#focus-item-id-13').click(function(){
    $('#focus-content-id-13').toggle('slow');
});
$('#focus-item-id-14').click(function(){
    $('#focus-content-id-14').toggle('slow');
});
$('#focus-item-id-15').click(function(){
    $('#focus-content-id-15').toggle('slow');
});
$('#focus-item-id-16').click(function(){
    $('#focus-content-id-16').toggle('slow');
});
$('#focus-item-id-17').click(function(){
    $('#focus-content-id-17').toggle('slow');
});
$('#focus-item-id-18').click(function(){
    $('#focus-content-id-18').toggle('slow');
});
$('#focus-item-id-19').click(function(){
    $('#focus-content-id-19').toggle('slow');
});
$('#focus-item-id-20').click(function(){
    $('#focus-content-id-20').toggle('slow');
});
$('#focus-item-id-21').click(function(){
    $('#focus-content-id-21').toggle('slow');
});
$('#focus-item-id-22').click(function(){
    $('#focus-content-id-22').toggle('slow');
});
$('#focus-item-id-23').click(function(){
    $('#focus-content-id-23').toggle('slow');
});
$('#focus-item-id-24').click(function(){
    $('#focus-content-id-24').toggle('slow');
});
$('#focus-item-id-25').click(function(){
    $('#focus-content-id-25').toggle('slow');
});
$('#focus-item-id-26').click(function(){
    $('#focus-content-id-26').toggle('slow');
});
$('#focus-item-id-27').click(function(){
    $('#focus-content-id-27').toggle('slow');
});
$('#focus-item-id-28').click(function(){
    $('#focus-content-id-28').toggle('slow');
});
$('#focus-item-id-29').click(function(){
    $('#focus-content-id-29').toggle('slow');
});
$('#focus-item-id-30').click(function(){
    $('#focus-content-id-30').toggle('slow');
});
$('#focus-item-id-31').click(function(){
    $('#focus-content-id-31').toggle('slow');
});
$('#focus-item-id-32').click(function(){
    $('#focus-content-id-32').toggle('slow');
});
$('#focus-item-id-33').click(function(){
    $('#focus-content-id-33').toggle('slow');
});
$('#focus-item-id-34').click(function(){
    $('#focus-content-id-34').toggle('slow');
});
$('#focus-item-id-35').click(function(){
    $('#focus-content-id-35').toggle('slow');
});